# Generated by Django 5.0.2 on 2024-02-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="content",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
